CREATE OR REPLACE VIEW ALMGR_COL_LOGS_ARCHIVED_VW AS
SELECT RL.ID ROW_LOG_ID,
         CL.ID COL_LOG_ID,
         EVENT_TIME,
         EVENT_TYPE_CODE,
         (SELECT NAME FROM ALMGR_EVENT_TYPES WHERE CODE = EVENT_TYPE_CODE) EVENT_NAME,
         SCHEMA_NAME,
         TABLE_NAME,
         RL.PK PRIMARY_KEY,
         COLUMN_NAME,
         VALUE_TYPE,
         OLD_VALUE,
         NEW_VALUE,         
         ORACLE_USER,
         OS_USER,
         APPL_USER,
         TERMINAL,
         PROGRAM,
         TRAN_NAME
    FROM ALMGR_ROW_LOGS_ARCHIVED RL,
         ALMGR_COL_LOGS_ARCHIVED CL
   WHERE RL.ID = CL.ROW_LOG_ID(+);
